server:
  port: 8080

spring:
  jpa:
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener.direct.acknowledge-mode: manual
    listener.simple.acknowledge-mode: manual
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  mustache:
    suffix: .html